export const DUEL_QUESTIONS: string[] = [
  "What's the last lie you told yourself that you still believe?",
  "Describe the moment you stopped being who you thought you were.",
  "What would you do differently if no one would ever know?",
  "What's the thing you've never said to someone you love?",
  "What are you pretending not to want?",
  "What part of yourself have you given up trying to fix?",
  "What would the child you were think of the adult you've become?",
  "What's the fear that lives underneath all your other fears?",
  "What's the most honest thing you've ever said out loud?",
  "What relationship are you staying in out of habit, not love?",
  "What would you confess if there were no consequences?",
  "Describe the moment you knew everything had changed.",
  "What do you miss about a version of yourself you've lost?",
  "What's the one decision you replay most often?",
  "What do people misunderstand most about you?",
  "When did you last feel completely real?",
  "What would make you feel truly known by another person?",
  "What are you waiting for permission to do?",
  "What truth have you been avoiding telling someone?",
  "What's the emotion you find hardest to admit?",
  "What do you do when no one is watching?",
  "What's the version of your life you abandoned?",
  "What would you change about how you were loved?",
  "What are you holding onto that you should let go?",
  "What did you inherit from your parents that you wish you hadn't?",
  "What does loneliness feel like for you, specifically?",
  "What's the thing about you that surprises people most?",
  "What's the version of yourself you're most ashamed of?",
  "What are you quietly grieving right now?",
  "What question do you most need someone to ask you?",
  "What would you tell yourself at sixteen?",
  "What would you stop doing if you were braver?",
  "What's the truth you've never said about your childhood?",
  "When did you know a relationship was over, really?",
  "What's the biggest risk you've never taken?",
  "What's the thing you want most and won't ask for?",
  "What does 'home' mean to you, honestly?",
  "What are you still angry about?",
  "What do you wish someone had said to you when you were hurting?",
  "What are you afraid people see when they look at you?",
  "What's the most important thing no one knows about you?",
  "Describe a moment when you chose yourself.",
  "What would you forgive yourself for if you could?",
  "What makes you feel most like yourself?",
  "What would you want written on your tombstone that no one would expect?",
  "What have you stopped believing in?",
  "What's the kindest thing you've done that no one witnessed?",
  "Where does your sadness live in your body?",
  "What's the story you tell about yourself that isn't true anymore?",
  "What would you do with one year left if no one could know how you spent it?",
];

export function getQuestion(index: number): string {
  return DUEL_QUESTIONS[index % DUEL_QUESTIONS.length];
}

export function randomQuestionIndex(): number {
  return Math.floor(Math.random() * DUEL_QUESTIONS.length);
}
